expressions=(
    # from https://www.indifferentlanguages.com/words/good_morning
    "Goeie more (Afrikaans)"
    "Miremengjes (Albanian)"
    "صباح الخير (Arabic)"
    "Բարի առավոտ (Armenian)"
    "Sabahınız xeyir (Azerbaijani)"
    "Egun on (Basque)"
    "Добрай раніцы (Belarusian)"
    "সুপ্রভাত (Bengali)"
    "Dobro jutro (Bosnian)"
    "Добро утро (Bulgarian)"
    "Bon dia (Catalan)"
    "Maayong buntag (Cebuano)"
    "M'mawa wabwino (Chichewa)"
    "早上好 (Chinese Simplified)"
    "早上好 (Chinese Traditional)"
    "Dobro jutro (Croatian)"
    "Dobré ráno (Czech)"
    "God morgen (Danish)"
    "Goedemorgen (Dutch)"
    "Bonan matenon (Esperanto)"
    "Tere hommikust (Estonian)"
    "Magandang umaga (Filipino)"
    "Hyvää huomenta (Finnish)"
    "Bonjour (French)"
    "Bos días (Galician)"
    "დილა მშვიდობისა (Georgian)"
    "Guten Morgen (German)"
    "Καλημέρα (Greek)"
    "સુપ્રભાત (Gujarati)"
    "Bonjou (Haitian Creole)"
    "Barka da safiya (Hausa)"
    "בוקר טוב (Hebrew)"
    "शुभ प्रभात (Hindi)"
    "Zoo thaum sawv ntxov (Hmong)"
    "Jó reggelt (Hungarian)"
    "Góðan daginn (Icelandic)"
    "Ụtụtụ ọma (Igbo)"
    "Selamat pagi (Indonesian)"
    "Maidin mhaith (Irish)"
    "Buongiorno (Italian)"
    "おはようございます (Japanese)"
    "Sugeng enjang (Javanese)"
    "ಶುಭೋದಯ (Kannada)"
    "Қайырлы таң (Kazakh)"
    "អរុណ​សួស្តី (Khmer)"
    "좋은 아침 (Korean)"
    "ສະ​ບາຍ​ດີ​ຕອນ​ເຊົ້າ (Lao)"
    "Bonum mane (Latin)"
    "Labrīt (Latvian)"
    "Labas rytas (Lithuanian)"
    "Добро утро (Macedonian)"
    "Salama (Malagasy)"
    "Selamat Pagi (Malay)"
    "സുപ്രഭാതം (Malayalam)"
    "Bongu (Maltese)"
    "ata pai (Maori)"
    "शुभ प्रभात (Marathi)"
    "өглөөний мэнд (Mongolian)"
    "မင်္ဂလာနံနက်ခင်းပါ (Myanmar (Burmese))"
    "शुभ - प्रभा(Nepali)"
    "God morgen (Norwegian)"
    "صبح بخیر (Persian)"
    "Dzień dobry (Polish)"
    "Bom Dia (Portuguese)"
    "Buna dimineata (Romanian)"
    "Доброе утро (Russian)"
    "Добро јутро (Serbian)"
    "Khotsong (Sesotho)"
    "සුභ උදෑසනක් (Sinhala)"
    "Dobré ráno (Slovak)"
    "Dobro jutro (Slovenian)"
    "Subax wanaagsan (Somali)"
    "Buenos días (Spanish)"
    "Habari za asubuhi (Swahili)"
    "God morgon (Swedish)"
    "Субҳ ба хайр (Tajik)"
    "காலை வணக்கம் (Tamil)"
    "శుభోదయం (Telugu)"
    "สวัสดีตอนเช้า (Thai)"
    "Günaydın (Turkish)"
    "Доброго ранку (Ukrainian)"
    "صبح بخیر (Urdu)"
    "Xayrli tong (Uzbek)"
    "Chào buổi sáng (Vietnamese)"
    "bore da (Welsh)"
    "גוט מארגן (Yiddish)"
    "E kaaro (Yoruba)"
    "Sawubona (Zulu)"
    )

# Seed random generator
RANDOM=$$$(date +%s)

selectedexpression=${expressions[($RANDOM % ${#expressions[@]})+1]}

echo "Good Morning!"
echo $selectedexpression
